source 'https://rubygems.org'

gem 'nginx_omniauth_adapter'
gem 'omniauth-github'
gem 'omniauth-slack',
    :git => 'git://github.com/3846masa/omniauth-slack.git',
    :branch => 'signin-with-slack-support'
gem 'unicorn'
